# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsongraph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='published',
            field=models.BooleanField(default=True, help_text="Unpublished topologies won't be updated or shown in the visualizer", verbose_name='published'),
        ),
    ]
