# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_netjsongraph.models.topology


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsongraph', '0002_topology_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='strategy',
            field=models.CharField(choices=[('fetch', 'FETCH'), ('receive', 'RECEIVE')], db_index=True, default='fetch', max_length=16, verbose_name='strategy'),
        ),
        migrations.AddField(
            model_name='topology',
            name='expiration_time',
            field=models.PositiveIntegerField(default=0, help_text='"Expiration Time" in seconds: setting this to 0 will immediately mark missing links as down; a value higher than 0 will delay marking missing links as down until the "modified" field of a link is older than "Expiration Time"', verbose_name='expiration time'),
        ),
        migrations.AddField(
            model_name='topology',
            name='key',
            field=models.CharField(blank=True, default=django_netjsongraph.models.topology.get_random_key, help_text='key needed to update topology from nodes ', max_length=64, verbose_name='key'),
        )
    ]
