# Generated by Django 2.0.1 on 2018-01-05 14:48
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsongraph', '0006_added_openvpn_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='status_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
