# Generated by Django 2.2.9 on 2019-12-30 07:29

from django.db import migrations

from . import migrate_addresses


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsongraph', '0008_create_new_address_field'),
    ]

    operations = [
        migrations.RunPython(migrate_addresses)
    ]
