# Generated by Django 2.2.9 on 2019-12-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsongraph', '0009_migrate_addresses_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='addresses_old',
        ),
    ]
